// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountPosts(ctx context.Context) (int64, error)
	CountPublishedPosts(ctx context.Context) (int64, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePost(ctx context.Context, id int64) error
	GetPost(ctx context.Context, id int64) (Post, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error)
	ListPublishedPosts(ctx context.Context, arg ListPublishedPostsParams) ([]Post, error)
	PublishPost(ctx context.Context, id int64) error
	UnpublishPost(ctx context.Context, id int64) error
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
}

var _ Querier = (*Queries)(nil)
